### ISSUE TITLE
Error while loading trained model

### ISSUE THREAD

**Issue by sainimohit23** [as-ideas/headliner#14]
I followed the documentation and got error for the following code:
> Training part
```
NUM_UNITS = 1024
BATCH_SIZE = 32
STEPS_PER_EPOCH = len(data) // BATCH_SIZE
STEPS_TO_LOG = 100
MAX_OUTPUT_LENGTH = 50
EPOCHS = 20
EMB_SIZE = 128

from headliner.trainer import Trainer
from headliner.model.summarizer_attention import SummarizerAttention

summarizer = SummarizerAttention(lstm_size=NUM_UNITS, embedding_size=EMB_SIZE)
trainer = Trainer(batch_size=BATCH_SIZE, 
                  steps_per_epoch=STEPS_PER_EPOCH, 
                  steps_to_log=STEPS_TO_LOG, 
                  max_output_len=MAX_OUTPUT_LENGTH, 
                  model_save_path=save_path)
trainer.train(summarizer, train, num_epochs=EPOCHS, val_data=test)

```

> Loading pre-trained model:

```
summarizer_loaded = SummarizerAttention.load('summarizer')
trainer = Trainer(batch_size=2)
trainer.train(summarizer_loaded, data)
```

```training an already initialized model...
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-20-1bcb176df5c9> in <module>()
      1 summarizer_loaded = SummarizerAttention.load('summarizer')
      2 trainer = Trainer(batch_size=2)
----> 3 trainer.train(summarizer_loaded, data)
      4 # summarizer_loaded.save('/tmp/summarizer_retrained')

C:\ProgramData\Anaconda3\lib\site-packages\headliner\trainer.py in train(self, summarizer, train_data, val_data, num_epochs, scorers, callbacks)
    203         train_step = summarizer.new_train_step(self.loss_function, self.batch_size, apply_gradients=True)
    204         while epoch_count < num_epochs:
--> 205             for train_source_seq, train_target_seq in train_dataset.take(-1):
    206                 batch_count += 1
    207                 current_loss = train_step(train_source_seq, train_target_seq)

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py in __next__(self)
    620 
    621   def __next__(self):  # For Python 3 compatibility
--> 622     return self.next()
    623 
    624   def _next_internal(self):

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py in next(self)
    664     """Returns a nested structure of `Tensor`s containing the next element."""
    665     try:
--> 666       return self._next_internal()
    667     except errors.OutOfRangeError:
    668       raise StopIteration

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py in _next_internal(self)
    649             self._iterator_resource,
    650             output_types=self._flat_output_types,
--> 651             output_shapes=self._flat_output_shapes)
    652 
    653       try:

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py in iterator_get_next_sync(iterator, output_types, output_shapes, name)
   2670       else:
   2671         message = e.message
-> 2672       _six.raise_from(_core._status_to_exception(e.code, message), None)
   2673   # Add nodes to the TensorFlow graph.
   2674   if not isinstance(output_types, (list, tuple)):

C:\ProgramData\Anaconda3\lib\site-packages\six.py in raise_from(value, from_value)

UnknownError: AttributeError: 'Vectorizer' object has no attribute 'max_input_len'
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 221, in __call__
    ret = func(*args)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 585, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "C:\ProgramData\Anaconda3\lib\site-packages\headliner\trainer.py", line 264, in <genexpr>
    data_vectorized = (vectorizer(d) for d in data_preprocessed)

  File "C:\ProgramData\Anaconda3\lib\site-packages\headliner\preprocessing\vectorizer.py", line 42, in __call__
    if self.max_input_len is not None:

AttributeError: 'Vectorizer' object has no attribute 'max_input_len'


	 [[{{node PyFunc}}]] [Op:IteratorGetNextSync]

```

**Comment by cschaefer26** [comment]
Hi, may it it be that you updated the library version before you tried to load the model? Unfortunately, we had to do some changes that are not backward compatible, i.e. we introduced the max_input_len which it is trying to load in your example.

**Comment by sainimohit23** [comment]
Earlier I was training the model on Tensorpad. Now, I am using kaggle kernels to train the model and its working fine. Closing this issue.
